IEEE-Std-1906: ns3::P1906MOLField Class Reference
ns3::P1906MOLField Class Reference
Base class implementing the Field component of the P1906 framework, dedicated to the MOLECULAR Example.
#include <p1906-mol-field.h>
Classes
struct simtime_t
simulated time structure anticipating other fields that may be required for time management
struct tubeCharacteristcs_t
properties of the microtubule network
Public Member Functions
void setTubeVolume (struct tubeCharacteristcs_t *ts, double volume=25)
Methods related to tube properties set the volume in which tubes will be generated.
void setTubeLength (struct tubeCharacteristcs_t *ts, double mean_tube_length=100)
set the mean tube length
void setTubeIntraAngle (struct tubeCharacteristcs_t *ts, double mean_intra_tube_angle=30)
set the mean angle between tube segments
void setTubeInterAngle (struct tubeCharacteristcs_t *ts, double mean_inter_tube_angle=10)
set the mean angle between entire tubes
void setTubeDensity (struct tubeCharacteristcs_t *ts, double mean_tube_density=10)
set the density of tube segments
void setTubePersistenceLength (struct tubeCharacteristcs_t *ts, double persistenceLength=50)
set the persistence length of the tubes
void setTubeSegments (struct tubeCharacteristcs_t *ts, size_t segPerTube=10)
set the number of segments per tube
void displayTubeChars (struct tubeCharacteristcs_t *ts)
display all the microtubule network properties
double propagationDelay (struct simtime_t *t)
Methods related to simulation time.
void initTime (struct simtime_t *t)
reset the simulation time
void updateTime (struct simtime_t *t, double event_time)
update the simulation given an event duration
void vectorFieldMeshMATLAB (gsl_matrix *vf, const char *fname)
Methods related to vector fields write the vector field in MATLAB format using regular spacing between samples.
void vectorFieldMeshMma (gsl_matrix *vf, const char *fname)
write the vector field in Mma format using regular spacing between samples
void findClosestPoint (gsl_vector *pt, gsl_matrix *vf, gsl_vector *result)
return closest point within threshold
void tubes2VectorField (gsl_matrix *tubeMatrix, gsl_matrix *vf)
convert the tube structures to a vector field of the same dimensions as the tubeMatrix
void activeNetworkProgrammability (gsl_matrix *vf, gsl_vector *pt)
compute and return the active network programmability metric at pt
void vectorFieldPlotMma (gsl_matrix *vf, const char *fname)
display the vector field in Mma format for VectorPlot3D
void vectorFieldPlotMATLAB (gsl_matrix *vf, const char *fname)
write a list of vectors into file fname in MATLAB loadable format
bool unitTestgetOverlap ()
Methods implementing unit tests test tube overlaps.
bool unitTestfindClosestPoint ()
test the findClosestPoint function
int brownianMotion (gsl_rng *r, gsl_vector *currentPos, gsl_vector *newPos, double timePeriod)
Methods related to Brownian motion in 3D newPos is Brownian motion from currentPos over timePeriod.
bool isPointOverlap (gsl_vector *pt, gsl_vector *segment)
true if pt insects segment, false otherwise
int freeFloat (gsl_rng *r, gsl_vector *startPt, gsl_matrix *pts, int time, double timePeriod, struct simtime_t *t)
Brownian motion from startPt for length time in timePeriod units; results returned in pts.
int float2Tube (gsl_rng *r, gsl_vector *startPt, gsl_matrix *pts, size_t *npts, gsl_matrix *tubeMatrix, double timePeriod, struct simtime_t *t)
free float until intersection with any tube
void point (gsl_vector *pt, double x, double y, double z)
Methods related to creating and displaying points and lines in 3D return a pt vector comprised of x, y, z.
void line (gsl_vector *line, gsl_vector *pt1, gsl_vector *pt2)
return a line comprised of two points
void line (gsl_matrix *line, int mp, gsl_vector *pt1, gsl_vector *pt2)
place a line comprised of pt1 and pt2 into a list of lines at position mp
void line (gsl_vector *segment, gsl_matrix *tubeMatrix, int mp)
retrieve segment mp from tubeMatrix and place it in segment
void displayPoints (gsl_matrix *pts)
simply print the list of points
void displayPoints (gsl_matrix *pts, size_t numPts)
print only the first numPts
void displayPoint (gsl_vector *pt)
simply print the value of a single point pt
void displayPos (gsl_vector *pts)
print a single position
void points2Mma (gsl_matrix *pts, size_t numPts, const char *fname)
write a list of points into file fname in Mathematica format
void connectedPoints2Mma (gsl_matrix *pts, size_t numPts, const char *fname)
write a list of connected points into file fname in Mathematica format
void plot2Mma (gsl_matrix *vals, const char *fname, const char *xlabel, const char *ylabel)
print a plot of x,y values in vals in Mathematica format into file fname
double distanceP (gsl_vector *pt1, gsl_vector *pt2)
return the distance between two points
double sEntropy (gsl_matrix *segAngle)
Methods related to computing structural entropy return the structural entropy give be a list of angles.
void cross_product (const gsl_vector *u, const gsl_vector *v, gsl_vector *product)
return the cross product of u and v in product, all vectors are the same size
double distance (gsl_vector *pt, gsl_vector *segment)
return the shortest distance in 3D space between the point pt and the segment
void motorWalk (gsl_rng *r, gsl_vector *startPt, gsl_matrix *pts, size_t *numPts, gsl_matrix *tubeMatrix, size_t segPerTube, struct simtime_t *t)
Methods related to walking along tubes and finding tube overlap walk along a specific tube identified by startPt and place result in pts.
size_t getAllOverlaps3D (gsl_matrix *tubeMatrix, gsl_matrix *pts)
return all the points where tubes overlap with one another in pts
int getOverlap3D (gsl_vector *segment, gsl_matrix *tubeMatrix, gsl_matrix *pts, gsl_vector *tubeSegments)
return all the points where a segment overlaps with a list of tubes in pts
int findNearestTube (gsl_vector *pt, gsl_matrix *tubeMatrix, double radius)
return the nearest segment in tubeMatrix to the point pt that falls within radius, otherwise -1
double genPersistenceLength (gsl_rng *r, gsl_matrix *segAngle, double segLength, double persistenceLength)
Methods related to generating and finding persistence length generate tube structure with a given segment and persistence length.
double getPersistenceLength (gsl_matrix *segMatrix)
compute the persistence length of a set of segments
void perstenceVersusEntropy (struct tubeCharacteristcs_t *ts, gsl_rng *r, gsl_vector *persistenceLengths)
plot persistence length versus structural entropy
void genTubes (struct tubeCharacteristcs_t *ts, gsl_rng *r, gsl_matrix *tubeMatrix)
Methods related to creating and displaying tubes fill tubeMatrix with random tubes in area with a given number of total segments and persistence length.
int genTube (struct tubeCharacteristcs_t *ts, gsl_rng *r, gsl_matrix *segMatrix, gsl_vector *startPt)
return the microtubule in segMatrix of a given persistence length starting at position startPt and it structural entropy in se
void displayTube (gsl_matrix *segMatrix)
simply print the end points of each segment of a tube
void tubes2Mma (gsl_matrix *tubeMatrix, size_t segPerTube, const char *fname)
write a list of tubes into file fname in Mathematica format
P1906MOLField ()
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::P1906Field
static TypeId GetTypeId (void)
Detailed Description
Base class implementing the Field component of the P1906 framework, dedicated to the MOLECULAR Example.
This class implements persistence length as described in: Bush, S. F., & Goel, S. (2013). Persistence Length as a Metric for Modeling and Simulation of Nanoscale Communication Networks, 31(12), 815-824. http://dx.doi.org/10.1109/JSAC.2013.SUP2.12130014.
The Gnu Scientific Library (GSL) is required for these methods. All points and positions are in three dimensions comprised of a gsl_vector * of length three (x, y, z). All lines and segments are comprised of two points within a gsl_vector * of length size (x1, y1, z1), (x2, y2, z2). Lists of points or positions are in a gsl_matrix * of size n x 3. Each tube is comprised of a list of segments within a gsl_matrix * of size s x 6 -> s x ((x1, y1, z1), (x2, y2, z2)). A set of tubes is also a gsl_matrix * of size (s * t) x 6, where s is the number of segments and t the number of tubes. All random number are derived from gsl_rng *.
Definition at line 75 of file p1906-mol-field.h.
Constructor & Destructor Documentation
ns3::P1906MOLField::P1906MOLField ()
This class implements persistence length as described in: Bush, S. F., & Goel, S. (2013). Persistence Length as a Metric for Modeling and Simulation of Nanoscale Communication Networks, 31(12), 815-824. http://dx.doi.org/10.1109/JSAC.2013.SUP2.12130014.
The Gnu Scientific Library (GSL) is required for these methods. All points and positions are in three dimensions comprised of a gsl_vector * of length three (x, y, z). All lines and segments are comprised of two points within a gsl_vector * of length size (x1, y1, z1), (x2, y2, z2). Lists of points or positions are in a gsl_matrix * of size n x 3. Each tube is comprised of a list of segments within a gsl_matrix * of size s x 6 -> s x ((x1, y1, z1), (x2, y2, z2)). A set of tubes is also a gsl_matrix * of size (s * t) x 6, where s is the number of segments and t the number of tubes. All random number are derived from gsl_rng *.
Next steps:
Todo:
document code and check into https://code.google.com/p/ieee-p1906-1-reference-code/source/browse/
Todo:
include whether the member should be in a different class, e.g. Motion
Todo:
gradient is the vector field as defined above at any point on a tube: length could be scaled to motor movement rate
Todo:
consider implementing Random Markov Field (RMF) for analysis of motor motion
Todo:
curve fit to tube segments to obtain vector field equation (vector field reconstruction) is currently done in separate Mathematica code
Todo:
implement active network programmability metric:
Todo:
relate structural entropy to energy, force, and chemical complexity
Todo:
add convection-diffusion using vector field lines
Todo:
could grow tubes from alternating ends so that starting point is in the center
Todo:
return propagation time: need to keep track of time
Todo:
consider many motors operating simultaneously: they would need to update simultaneously
Todo:
plot motor starting in random location versus time to reach destination as function of tube structure
Todo:
plot structural entropy versus delay
Todo:
plot binding time versus delay
Todo:
plot distance travelled versus delay, structural entropy, etc.
properties of the microtubule network
set the microtubule network properties
simulated time
reset the simulated time
random number generation structures and initialization
display all the microtubule network properties
create a given density of tubes of numSegments in given volume volume starts at 0, 0, 0 to volume^(1/3) in each dimension
find tube overlap points the maximum number of overlaps for n lines is n^2
holds the vector field
print the vector field
random motion for 100 sec start near the first tube
move randomly until overlap with tube
now walk along the tube
see http://www.gnu.org/software/gsl/manual/html_node/Level-3-GSL-BLAS-Interface.html#Level-3-GSL-BLAS-Interface
test segment overlap
test plotting points
close down field activity
Definition at line 45 of file p1906-mol-field.cc.
References connectedPoints2Mma(), displayPoint(), displayTubeChars(), distance(), float2Tube(), freeFloat(), genTubes(), getAllOverlaps3D(), getOverlap3D(), initTime(), isPointOverlap(), line(), motorWalk(), ns3::P1906MOLField::tubeCharacteristcs_t::numTubes, perstenceVersusEntropy(), plot2Mma(), point(), points2Mma(), ns3::P1906MOLField::tubeCharacteristcs_t::segPerTube, setTubeDensity(), setTubeInterAngle(), setTubeIntraAngle(), setTubeLength(), setTubePersistenceLength(), setTubeSegments(), setTubeVolume(), tubes2Mma(), tubes2VectorField(), vectorFieldMeshMATLAB(), and vectorFieldPlotMma().
Member Function Documentation
void ns3::P1906MOLField::activeNetworkProgrammability (gsl_matrix * vf, gsl_vector * pt)
compute and return the active network programmability metric at pt
Todo:
implement the standard active network programmability metric
Todo:
use vector field and divergence to compute this value
sum the vector input and output to point pt may add a radius argument to define a sphere for determining flux through the surface of the sphere activeNetworkProgrammability is fundamentally a change to the vector field
Definition at line 225 of file p1906-mol-field.cc.
int ns3::P1906MOLField::brownianMotion (gsl_rng * r, gsl_vector * currentPos, gsl_vector * newPos, double timePeriod)
Methods related to Brownian motion in 3D newPos is Brownian motion from currentPos over timePeriod.
return newPos based upon Brownian motion from currentPos over timePeriod
Todo:
this should be in Motion class
the new position is Gaussian with variance proportional to time taken: W_t - W_s ~ N(0, t - s)
Definition at line 1156 of file p1906-mol-field.cc.
References point().
void ns3::P1906MOLField::connectedPoints2Mma (gsl_matrix * pts, size_t numPts, const char * fname)
write a list of connected points into file fname in Mathematica format
print the points (vertices) in pts in Mathematica format into file fname and include edges between the vertices
option to print vertex labels fprintf (pFile, "}, VertexLabeling -> True]\n");
Definition at line 803 of file p1906-mol-field.cc.
void ns3::P1906MOLField::cross_product (const gsl_vector * u, const gsl_vector * v, gsl_vector * product)
return the cross product of u and v in product, all vectors are the same size
the vector cross product is normal to the input vectors and has magnitude equivalent to the volume of a parallelogram formed by the input vectors u and v are the input vectors and product is the output vector
Definition at line 517 of file p1906-mol-field.cc.
void ns3::P1906MOLField::displayPoint (gsl_vector * pt)
simply print the value of a single point pt
print the point pt
Definition at line 887 of file p1906-mol-field.cc.
void ns3::P1906MOLField::displayPoints (gsl_matrix * pts)
simply print the list of points
print the points in pts
Definition at line 791 of file p1906-mol-field.cc.
void ns3::P1906MOLField::displayPoints (gsl_matrix * pts, size_t numPts)
print only the first numPts
print the first numPts points pts
Definition at line 896 of file p1906-mol-field.cc.
void ns3::P1906MOLField::displayPos (gsl_vector * pts)
print a single position
print the position pts
Definition at line 906 of file p1906-mol-field.cc.
void ns3::P1906MOLField::displayTube (gsl_matrix * segMatrix)
simply print the end points of each segment of a tube
print the tube segments in segMatrix
Definition at line 778 of file p1906-mol-field.cc.
void ns3::P1906MOLField::displayTubeChars (tubeCharacteristcs_t * ts)
display all the microtubule network properties
print tube characteristics to standard output
Definition at line 333 of file p1906-mol-field.cc.
References ns3::P1906MOLField::tubeCharacteristcs_t::mean_inter_tube_angle, ns3::P1906MOLField::tubeCharacteristcs_t::mean_intra_tube_angle, ns3::P1906MOLField::tubeCharacteristcs_t::mean_tube_density, ns3::P1906MOLField::tubeCharacteristcs_t::mean_tube_length, ns3::P1906MOLField::tubeCharacteristcs_t::numSegments, ns3::P1906MOLField::tubeCharacteristcs_t::segLength, and ns3::P1906MOLField::tubeCharacteristcs_t::volume.
double ns3::P1906MOLField::distance (gsl_vector * pt, gsl_vector * segment)
return the shortest distance in 3D space between the point pt and the segment
return the shortest distance between point pt and the line or point segment_or_point if segment_or_point is a vector of length 3, then it is a point if segment_or_point is a vector of length 6, then it is a line segment described by two end points
distance = |pt - pt1| x |pt - pt2| / |pt2 - pt1| where x is the cross product
Definition at line 450 of file p1906-mol-field.cc.
References cross_product(), and point().
double ns3::P1906MOLField::distanceP (gsl_vector * pt1, gsl_vector * pt2)
return the distance between two points
return the distance between two point pt1 and point pt2
copy pt1 to d
subtract pt2 from pt1 in d
return the Euclidean distance
Definition at line 435 of file p1906-mol-field.cc.
void ns3::P1906MOLField::findClosestPoint (gsl_vector * pt, gsl_matrix * vf, gsl_vector * result)
return closest point within threshold
return the location of the vector from vf that is closest to the point pt in result
the current closest point
the current closest vector
the test point
display the vector field
test the next vector field location
tpt is point under test from vector field cpt is the current shortest distance point
update the location and vector if closer
return the result
Definition at line 1282 of file p1906-mol-field.cc.
References distance(), and point().
int ns3::P1906MOLField::findNearestTube (gsl_vector * pt, gsl_matrix * tubeMatrix, double radius)
return the nearest segment in tubeMatrix to the point pt that falls within radius, otherwise -1
return the index of the nearest tube in tubeMatrix within a given radius from pt otherwise return -1
Definition at line 412 of file p1906-mol-field.cc.
References distance(), and line().
int ns3::P1906MOLField::float2Tube (gsl_rng * r, gsl_vector * startPt, gsl_matrix * pts, size_t * npts, gsl_matrix * tubeMatrix, double timePeriod, simtime_t * t)
free float until intersection with any tube
motor is unbound from tube and floats via Brownian motion until it makes contact with a tube pts - locations of the motor during its random walk comprised of npts startPt - where the motor began its random walk timePeriod - length of each step of the walk returns the index of the contact segment in tubeMatrix
Todo:
this should be in Motion class
total number of points traversed
end after this many steps
nearest tube segment
begin at the starting point
float to the nearest tube within a given radius
consider starting position the first point
Definition at line 641 of file p1906-mol-field.cc.
References brownianMotion(), findNearestTube(), point(), and updateTime().
int ns3::P1906MOLField::freeFloat (gsl_rng * r, gsl_vector * startPt, gsl_matrix * pts, int time, double timePeriod, simtime_t * t)
Brownian motion from startPt for length time in timePeriod units; results returned in pts.
implements a motor floating via Brownian motion for time steps with step lengths of timePeriod
Todo:
this should be in Motion class
Definition at line 682 of file p1906-mol-field.cc.
References brownianMotion(), point(), and updateTime().
double ns3::P1906MOLField::genPersistenceLength (gsl_rng * r, gsl_matrix * segAngle, double segLength, double persistenceLength)
Methods related to generating and finding persistence length generate tube structure with a given segment and persistence length.
generate angles for a structure with the given persistence length and segment length and return the angles in setAngle
the angle distribution is Gaussian with zero mean and variance , where is persistence length and is the segment length; angles are in radians
See http://www.uic.edu/classes/phys/phys450/MARKO/N015.html.
Fortunately there is a relation that we can take advantage of to figure out the stiffness of the torsion spring between each segment. This relation is . From this we can see that the persistence length is a characteristic length scale that relates the bending rigidity of the DNA chain to the thermal energy. Larger persistence lengths indicate a stiffer chain that is less susceptible to thermal fluctuations.
What we're interested in, of course, is the energy cost for bending the DNA into the nice round coil it must be in to fit in the capsid. Like a linear spring where the energy is of the form , the energy to bend the DNA chain is of the form , where is the derivative of the tangent vector to each Kuhn segment of the chain. Since the chain is being bent into a circle of radius , , and thus the bending energy is . If we assume that all of the DNA is coiled around the outer radius of the capsid (R = 42 nm), then the energy cost due to bending is . Note that this is approximately the same energy cost as we found for the loss of entropy. From the model shown on the first page of the website, you may have noticed that some of the DNA is in fact coiled at smaller radii than the outermost "shell". The energy cost for bending that part of the DNA will be much higher since E is proportional to , but even so, it is unlikely that this energy cost greatly exceeds .
Ref: Multiscale Modeling in Biomechanics and Mechanobiology edited by Suvranu De, Wonmuk Hwang, Ellen Kuh pp. 68-69
a radian is 180/Pi degrees
Definition at line 1511 of file p1906-mol-field.cc.
References sEntropy().
int ns3::P1906MOLField::genTube (tubeCharacteristcs_t * ts, gsl_rng * r, gsl_matrix * segMatrix, gsl_vector * startPt)
return the microtubule in segMatrix of a given persistence length starting at position startPt and it structural entropy in se
create and return a microtubule of given persistence length in segMatrix and its structural entropy in se
for 3D consider generating two angles per tube: and in spherical coordinates, length is already specified x = r sin cos y = r sin sin z = r cos
Todo:
randomize initial tube orientations
set the start points of the segment
use starting coordinates
use end of last segment
set the end points of the segment
Definition at line 1447 of file p1906-mol-field.cc.
References genPersistenceLength(), ns3::P1906MOLField::tubeCharacteristcs_t::numSegments, ns3::P1906MOLField::tubeCharacteristcs_t::persistenceLength, ns3::P1906MOLField::tubeCharacteristcs_t::se, ns3::P1906MOLField::tubeCharacteristcs_t::segLength, ns3::P1906MOLField::tubeCharacteristcs_t::segPerTube, and sEntropy().
void ns3::P1906MOLField::genTubes (tubeCharacteristcs_t * ts, gsl_rng * r, gsl_matrix * tubeMatrix)
Methods related to creating and displaying tubes fill tubeMatrix with random tubes in area with a given number of total segments and persistence length.
generate a set of tubes comprised of a total of numSegments in volume with segPerTube segments of segLength and persistenceLength and return in tubeMatrix
Todo:
genTube* could be moved to start of ns-3 or each tube could be an ns-3 node
Todo:
get actual tube graph properties from biologist
hold the values for a tube comprised of many segments: x_start y_start x_start x_end y_end z_end
volume starts at 0, 0, 0 to volume^(1/3) in each dimension
set the starting location for the tube
create a single tube of many segments
copy tube segments to main tube matrix
Definition at line 707 of file p1906-mol-field.cc.
References genTube(), ns3::P1906MOLField::tubeCharacteristcs_t::numTubes, point(), ns3::P1906MOLField::tubeCharacteristcs_t::se, ns3::P1906MOLField::tubeCharacteristcs_t::segPerTube, and ns3::P1906MOLField::tubeCharacteristcs_t::volume.
size_t ns3::P1906MOLField::getAllOverlaps3D (gsl_matrix * tubeMatrix, gsl_matrix * pts)
return all the points where tubes overlap with one another in pts
return all overlapping points in tubeMatrix in the list of points pts
move segment from tubes to segment
check for overlap
store overlapping points
Definition at line 1004 of file p1906-mol-field.cc.
References getOverlap3D().
int ns3::P1906MOLField::getOverlap3D (gsl_vector * segment, gsl_matrix * tubeMatrix, gsl_matrix * pts, gsl_vector * tubeSegments)
return all the points where a segment overlaps with a list of tubes in pts
return the number of overlapping points in pts and the index of the tubeMatrix segments overlapped in tubeSegments
all points defined by x, y, z values line A -> B: (a1, a2, a3) -> (b1, b2, b3) line C -> D: (c1, c2, c3) -> (d1, d2, d3)
solve: a1 + t * (b1 - a1) == c1 + s * (d1 - c1) a2 + t * (b2 - a2) == c2 + s * (d2 - c2) a3 + t * (b3 - a3) == c3 + s * (d3 - c3)
A x = b where x(0) = t and x(1) = s (b1 - a1) * t - (d1 - c1) * s == c1 - a1 (b2 - a2) * t - (d2 - c2) * s == c2 - a2 (b3 - a3) * t - (d3 - c3) * s == c3 - a3
A is M x N work is tmp storage of length N, A is replaced with U, V is N x N, S is M x N
if x(0) = t, x(1) = s exist, then substitute and solve for overlapping point
the segments only overlap if their lengths are long enough
A <= x <= B and C <= x <= D
Definition at line 1038 of file p1906-mol-field.cc.
double ns3::P1906MOLField::getPersistenceLength (gsl_matrix * segMatrix)
compute the persistence length of a set of segments
Todo:
never implemented; may not be needed
segMatrix rows are x_start x_end y_start y_end (may not need numSegments)
may not need this method
Definition at line 1554 of file p1906-mol-field.cc.
void ns3::P1906MOLField::initTime (simtime_t * t)
reset the simulation time
initialize simulation time
Definition at line 321 of file p1906-mol-field.cc.
References ns3::P1906MOLField::simtime_t::time.
bool ns3::P1906MOLField::isPointOverlap (gsl_vector * pt, gsl_vector * segment)
true if pt insects segment, false otherwise
return true if point pt lies on segment, false otherwise
Todo:
this should be in Motion class
Determine whether the points A(2,4,2) B(3,7,-3) and C(1,3,3) lie on a straight line. Start by determining a direction vector AB = [a, b, c] for the line connecting points A and B. This vector gives the slopes of the three parametric equations describing the line between the points. AB = [ x, y, z] = [3 - 2, 7 - 4, -3 - 2] = [1, 3, -5]. Three parametric equations for a line are: x = x1 + at y = y1 + bt z = z1 + ct, So if we let A = (x1, y1, z1) x = 2 + t y = 4 + 3t z = 2 - 5t These three parametric equations describe the line connecting A and B. To see if C is on this line, we can substitute its x coordinate into the x parametric equation to find t: 1 = 2 + t, so t = -1. Now substitute this t into the other two equations: y = 4 + 3(-1) = 1; z = 2 - 5(-1) = 7. So (1, 1, 7) is a point on the line, but C = (1, 3, 3) is not.
direction vector
slope of each dimension
Definition at line 585 of file p1906-mol-field.cc.
void ns3::P1906MOLField::line (gsl_vector * line, gsl_vector * pt1, gsl_vector * pt2)
return a line comprised of two points
set line with end points pt1 and pt2
Definition at line 751 of file p1906-mol-field.cc.
void ns3::P1906MOLField::line (gsl_matrix * line, int mp, gsl_vector * pt1, gsl_vector * pt2)
place a line comprised of pt1 and pt2 into a list of lines at position mp
set the segment at location mp in the line matrix with pt1 and pt2
Definition at line 768 of file p1906-mol-field.cc.
void ns3::P1906MOLField::line (gsl_vector * segment, gsl_matrix * tubeMatrix, int mp)
retrieve segment mp from tubeMatrix and place it in segment
return the segment in location mp from tubeMatrix
Definition at line 761 of file p1906-mol-field.cc.
void ns3::P1906MOLField::motorWalk (gsl_rng * r, gsl_vector * startPt, gsl_matrix * pts, size_t * numPts, gsl_matrix * tubeMatrix, size_t segPerTube, simtime_t * t)
Methods related to walking along tubes and finding tube overlap walk along a specific tube identified by startPt and place result in pts.
Todo:
this should be in Motion class
Todo:
verify that motorWalk is working properly
See "Movements of Molecular Motors," Reinhard Lipowsky movement speed: ~1 um / sec bound time ~2 sec assumes startPt is on a tube in tubeMatrix
                          nm / sec
double bindingTime = 2; sec
find the tube the motor is starting on
Todo:
set tube radius (thickness) globally
store the starting point
walk along tube for distance determined by bound time segments are sequential in tubeMatrix of length segPerTube
the segment within the tube
segments until end of tube
walk to end of segment
Definition at line 534 of file p1906-mol-field.cc.
References distanceP(), findNearestTube(), line(), point(), and updateTime().
void ns3::P1906MOLField::perstenceVersusEntropy (tubeCharacteristcs_t * ts, gsl_rng * r, gsl_vector * persistenceLengths)
plot persistence length versus structural entropy
plot the results
Definition at line 390 of file p1906-mol-field.cc.
References genTubes(), ns3::P1906MOLField::tubeCharacteristcs_t::numTubes, plot2Mma(), ns3::P1906MOLField::tubeCharacteristcs_t::se, ns3::P1906MOLField::tubeCharacteristcs_t::segPerTube, setTubePersistenceLength(), and tubes2Mma().
void ns3::P1906MOLField::plot2Mma (gsl_matrix * vals, const char * fname, const char * xlabel, const char * ylabel)
print a plot of x,y values in vals in Mathematica format into file fname
ListLinePlot[Quantity[{0, 3, 6, 8, 10, 11, 11, 16, 20, 22}, "Centimeters"], AxesLabel -> Automatic]
Definition at line 862 of file p1906-mol-field.cc.
void ns3::P1906MOLField::point (gsl_vector * pt, double x, double y, double z)
Methods related to creating and displaying points and lines in 3D return a pt vector comprised of x, y, z.
set point pt with x, y, and z coordinates
Definition at line 743 of file p1906-mol-field.cc.
void ns3::P1906MOLField::points2Mma (gsl_matrix * pts, size_t numPts, const char * fname)
write a list of points into file fname in Mathematica format
print the first numPts points pts in Mathematica format in file fname
Definition at line 841 of file p1906-mol-field.cc.
double ns3::P1906MOLField::propagationDelay (simtime_t * t)
Methods related to simulation time.
return simulation time
Todo:
return the propagation delay for a motor
Definition at line 315 of file p1906-mol-field.cc.
References ns3::P1906MOLField::simtime_t::time.
double ns3::P1906MOLField::sEntropy (gsl_matrix * segAngle)
Methods related to computing structural entropy return the structural entropy give be a list of angles.
return the information entropy of a tube segment defined by its list of angles in segAngle
bin the values in order to find P(x) see gsl_histogram_pdf * gsl_histogram_pdf_alloc (size_t n) see https://www.gnu.org/software/gsl/manual/html_node/The-histogram-probability-distribution-struct.html
get the max segAngle
printf ("segAngle(%ld,%ld) = %g\t", i, j, gsl_matrix_get (segAngle, i, j)); */
printf("p = %g\n", p);
printf("H = %g\n", H);
gsl_histogram_fprintf (stdout, h, "%g", "%g");
Definition at line 1564 of file p1906-mol-field.cc.
void ns3::P1906MOLField::setTubeDensity (tubeCharacteristcs_t * ts, double mean_tube_density = 10)
set the density of tube segments
this is really the segment density
Definition at line 370 of file p1906-mol-field.cc.
References ns3::P1906MOLField::tubeCharacteristcs_t::mean_tube_density, ns3::P1906MOLField::tubeCharacteristcs_t::numSegments, and ns3::P1906MOLField::tubeCharacteristcs_t::volume.
void ns3::P1906MOLField::setTubeInterAngle (tubeCharacteristcs_t * ts, double mean_inter_tube_angle = 10)
set the mean angle between entire tubes
set the mean angle between tubes
Definition at line 364 of file p1906-mol-field.cc.
References ns3::P1906MOLField::tubeCharacteristcs_t::mean_inter_tube_angle.
void ns3::P1906MOLField::setTubeIntraAngle (tubeCharacteristcs_t * ts, double mean_intra_tube_angle = 30)
set the mean angle between tube segments
set the mean angle between segments of the tube
Definition at line 358 of file p1906-mol-field.cc.
References ns3::P1906MOLField::tubeCharacteristcs_t::mean_intra_tube_angle.
void ns3::P1906MOLField::setTubePersistenceLength (tubeCharacteristcs_t * ts, double persistenceLength = 50)
set the persistence length of the tubes
set the persistence length of each tube
Definition at line 377 of file p1906-mol-field.cc.
References ns3::P1906MOLField::tubeCharacteristcs_t::persistenceLength.
void ns3::P1906MOLField::setTubeVolume (tubeCharacteristcs_t * ts, double volume = 25)
Methods related to tube properties set the volume in which tubes will be generated.
set the volume in which tube centers exist
Todo:
the setTube* functions could be specified before ns-3 starts and exist as ns-3 nodes
Definition at line 345 of file p1906-mol-field.cc.
References ns3::P1906MOLField::tubeCharacteristcs_t::volume.
void ns3::P1906MOLField::tubes2Mma (gsl_matrix * tubeMatrix, size_t segPerTube, const char * fname)
write a list of tubes into file fname in Mathematica format
print all tubes in tubeMatrix into a Mathematica file fname with segments per tube of segPerTube
save tubes to file in the form of GraphPlot3D[{1 -> 2, 1 -> 4, 1 -> 5, 2 -> 3, 2 -> 6, 3 -> 4, 3 -> 7, 4 -> 8, 5 -> 6, 5 -> 8, 6 -> 7, 7 -> 8}, VertexCoordinateRules -> {1 -> {0, 1, 2}, 2 -> {-1, 0, 2}, 3 -> {0, -1, 2}, 4 -> {1, 0, 2}, 5 -> {0, 2, 0}, 6 -> {-2, 0, 0}, 7 -> {0, -2, 0}, 8 -> {2, 0, 0}}]
fprintf (pFile, "numTubes: %ld segPerTube: %ld\n", numTubes, segPerTube);
only print the ends after the first one
option to print vertex labels fprintf (pFile, "}, VertexLabeling -> True]\n");
Definition at line 1386 of file p1906-mol-field.cc.
void ns3::P1906MOLField::tubes2VectorField (gsl_matrix * tubeMatrix, gsl_matrix * vf)
convert the tube structures to a vector field of the same dimensions as the tubeMatrix
return vector field vf based upon tubes in tubeMatrix
Definition at line 289 of file p1906-mol-field.cc.
bool ns3::P1906MOLField::unitTestfindClosestPoint ()
test the findClosestPoint function
a unit test of the findClosestPoint function
Definition at line 915 of file p1906-mol-field.cc.
References findClosestPoint(), and point().
bool ns3::P1906MOLField::unitTestgetOverlap ()
Methods implementing unit tests test tube overlaps.
a unit test for getOverlap
Todo:
create unit tests
Test 1: Simple cross
Test 2: Moving cross
convert theta to x, y values
Test 2: Rotating segment
Definition at line 966 of file p1906-mol-field.cc.
References displayPoints(), getOverlap3D(), line(), and point().
void ns3::P1906MOLField::updateTime (simtime_t * t, double event_time)
update the simulation given an event duration
update simulation time
Definition at line 327 of file p1906-mol-field.cc.
References ns3::P1906MOLField::simtime_t::time.
void ns3::P1906MOLField::vectorFieldMeshMATLAB (gsl_matrix * vf, const char * fname)
Methods related to vector fields write the vector field in MATLAB format using regular spacing between samples.
write the vector field in MATLAB format using regular spacing between samples in the file fname The result of this file is loaded into Mathematica and the vector field is reconstructed from the samples via interpolation Then the vector field operators are applied - see bushs.nosp@m.f@re.nosp@m.searc.nosp@m.h.ge.nosp@m..com for results
extract the location and vector components from the field
find the min and max values for each component
step through equidistant points in a volume and store the vector values at each point
find the closest point to the current location
check if distance within range
if not, store the null vector
otherwise, store the vector value
print current location and stored vector value
Definition at line 1173 of file p1906-mol-field.cc.
References distance(), findClosestPoint(), and point().
void ns3::P1906MOLField::vectorFieldMeshMma (gsl_matrix * vf, const char * fname)
write the vector field in Mma format using regular spacing between samples
write the vector field in Mathematica format using regular spacing between samples in file fname
fprintf (pFile, "}, "); fprintf (pFile, ", PlotStyle -> {Dashed, Thick, Red}");
option to print vertex labels fprintf (pFile, "}, VertexLabeling -> True]\n");
Definition at line 261 of file p1906-mol-field.cc.
void ns3::P1906MOLField::vectorFieldPlotMma (gsl_matrix * vf, const char * fname)
display the vector field in Mma format for VectorPlot3D
display the vector field in Mathematica format for VectorPlot3D in file fname
fprintf (pFile, "}, "); fprintf (pFile, ", PlotStyle -> {Dashed, Thick, Red}");
option to print vertex labels fprintf (pFile, "}, VertexLabeling -> True]\n");
Definition at line 233 of file p1906-mol-field.cc.
The documentation for this class was generated from the following files:
model-mol/p1906-mol-field.h
model-mol/p1906-mol-field.cc